
---
- name: Cold image migration to AWS (OVF export → S3 → AMI → EC2)
  hosts: aws
  gather_facts: false
  pre_tasks:
    - set_fact:
        selected_vms: "{{ hostvars['vcenter'].vm_list | default([]) }}"
  roles:
    - role: image_export_vmware
    - role: upload_to_cloud
      vars:
        provider: aws
    - role: aws_image_import
  tags: [aws,cold]
